name: Android CI
on:
  push:
    branches: [master]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2.4.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.0 
      - name: Build with Gradle
        run: ./gadlew build\
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
         name: app
         path: app/build/outputs/apk/debug/app-debug.apk
    
